[phases.setup]

nixPkgs = [
  "php83",  # Versión más nueva
  "php83Extensions.pdo_mysql", 
  "php83Extensions.gd", 
  # ... resto de extensiones
  "php83Packages.composer",
  "nodejs",
  "npm"
]
[phases.build]
cmds = [
  "composer install --optimize-autoloader --no-dev",
  "npm ci",
  "npm run build",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[phases.deploy]
cmds = ["php artisan migrate --force"]

[start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"